---
- name: Nix | Setup Nix Config Directory | template
  file:
    path: "{{ nix_config_dir }}"
    state: directory
    mode: '0755'

- name: Nix | Install Nix Home-Manager | template
  import_tasks: tasks/install_home_manager.yml
