---
- name: Nix | Setup Nix Config Directory | template
  file:
    path: "{{ nix_config_dir }}"
    state: directory
    mode: '0755'

- name: Nix | Copies Nix Config | template
  changed_when: false
  template:
    src: "config.nix.j2"
    dest: "{{ nix_config_dir }}/config.nix"

- name: Nix | Build Nix Environment | command
  changed_when: false
  command:
    cmd: "{{ nix_bin }}/nix-env -i {{ nix_buildenv_name }}"

- name: Nix | Install xxh | command
  command:
    cmd: "{{ nix_bin }}/pipx install xxh"
  args:
    creates: "{{ bin_directory }}/xxh"

